### ISSUE TITLE
Feature request: Preserve user role for users already exist in WordPress

### ISSUE THREAD

**Issue by Jamesits** [psignoret/aad-sso-wordpress#101]
With Azure AD group to WP role association enabled, I set the admin's email address to match that in AAD, then tried to login via AAD. Then my admin account is set to be a subscriber, and I lost control over my site. Have to alter the database manually to regain admin privileges.

**Comment by psignoret** [comment]
The behavior you described is what is exactly what is intended (the Azure AD group membership, or lack thereof, in this case overriding the previous role persisted in WP. Did you expect something different?

**Comment by psignoret** [comment]
@Jamesits I'm going to close this issue for now, but if you have any follow-up questions or additional details to share, please feel free to re-open it.
