### ISSUE TITLE
External user support

### ISSUE THREAD

**Issue by petervankoesveld** [psignoret/aad-sso-wordpress#103]
Hi,

Currently I'm investigating AAD integration with Wordpress.

My rowing club is currently using Office 365 to collaborate on documents. Eventually they want to share documents with members of the rowing (not all the users have access to Office 365 due licensing). Anonymous sharing is risky due the classification of the documents, we'd like to authenticate the members who access the documents.

Does anyone have experience with this plugin in the case I described?

**Comment by psignoret** [comment]
Are these you want to collaborate on documents on SharePoint Online?

**Comment by petervankoesveld** [comment]
@psignoret Correct the documents are in SharePoint Online. Users without an Office 365 license just need to view the documents.

**Comment by psignoret** [comment]
Have you considered just using SharePoint Online's external sharing capability? https://support.office.com/en-us/article/Manage-external-sharing-for-your-SharePoint-Online-environment-c8a462eb-0723-4b0b-8d0a-70feafe4be85

External users don't require licences to SharePoint or Office 365.

What did you have in mind for using WordPress to collaborate on these documents?

**Comment by psignoret** [comment]
@petervankoesveld I'm going to close this issue for now, but if you have any more details or questions for this, please feel free to re-open it.
