### ISSUE TITLE
AAD Permissions

### ISSUE THREAD

**Issue by mrdenny** [psignoret/aad-sso-wordpress#105]
In the docs you say that two permissions are needed in AAD, but I found that only the "Sign in and read user profile" permission is needed. Any more permissions than that will throw an error for non-admin users.

**Comment by psignoret** [comment]
The docs mention that "Read directory data" (Directory.Read.All) is only needed if the signed-in user's group membership will be mapped to WordPress roles. In reality, the minimum needed for this is the new(ish) permission "Read all groups" (Group.Read.All), but that permissions is still marked as "preview".

In any case, both of these permissions (Directory.Read.All and Group.Read.All) require administrator consent.. #32 is tracking a feature to improve the guidance (e.g. provide a shareable link that triggers admin consent on behalf of all users) for this.

You can read more about Azure AD Graph API permissions here: https://msdn.microsoft.com/library/azure/ad/graph/howto/azure-ad-graph-api-permission-scopes
