### ISSUE TITLE
AAD B2C

### ISSUE THREAD

**Issue by mrdenny** [psignoret/aad-sso-wordpress#106]
I didn't see anything about this in the questions so far, or the docs.  Is Azure B2C supported with this solution?

**Comment by psignoret** [comment]
No, Azure AD B2C is not supported by this plugin at the moment. #70 (which you can find by [searching](https://github.com/psignoret/aad-sso-wordpress/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20b2c) issues for "B2C") is tracking this, but it is not in the immediate priority list.

If you need B2C support, you may want to look at [AzureAD/active-directory-b2c-wordpress-plugin-openidconnect](https://github.com/AzureAD/active-directory-b2c-wordpress-plugin-openidconnect), though I'm not sure if that is being actively developed.

**Comment by cedrox** [comment]
Not so much update on _active-directory-b2c-wordpress-plugin-openidconnect_... Is there any other alternative out there ?

**Comment by psignoret** [comment]
Have you tried it, though? Have you run into any issues?
