### ISSUE TITLE
Azure AD is just redirecting back to WordPress login page

### ISSUE THREAD

**Issue by mrdenny** [psignoret/aad-sso-wordpress#107]
One of the sites which I've setup AAD for using this plugin is just being redirected back to the WordPress login page when I try to authenticate using AAD.  I had AAD setup to auto redirect but that was just getting into a redirection loop. When I disabled the plugin and logged in via WordPress auth and enabled the plugin then went into the settings and disabled the auto redirect, when I click the link on the home page to be directed to AAD it just kicks me back to the login page.

Nothing has changed in the site (thankfully it's a dev version of our site) and nothing was changed in AAD.  There's no error being displayed anywhere that I can see.  When I look in the logs in AAD I see no login attempts or errors being logged.

**Comment by mrdenny** [comment]
And today it's just fine with no issues. Makes no sense as nothing has been changed.

**Comment by psignoret** [comment]
Indeed, it does not make too much sense. Feel free to re-open this issue if it comes up again.
