### ISSUE TITLE
SSO from Wordpress to 365 Email

### ISSUE THREAD

**Issue by bigbydesign** [psignoret/aad-sso-wordpress#111]
I couldn't find anyone asking about this or any specifics in the project. Once the token has been generated will it allow you to put a link to 365 email on your Wordpress site so that users can use email without re-authenticating?

Thanks,

Andy

**Comment by psignoret** [comment]
You mean a link to https://www.outlook.com/contoso.com (where contoso.com is you company's domain name)?

**Comment by bigbydesign** [comment]
Philippe,

This code really is not SSO as you have to fill out the username/password
twice? I want to be able to fill out the username/pass on the Wordpress
login page and then be able to access o365. Your code only "hooks" the
Azure AD login to Wordpress. It really can't be characterized by SSO as you
login twice? What about leveraging the adal.AuthenticationContext and
acquire_token_with_username_password?
Then you would be getting a token without the user being redirected and
behind the scenes.

Thanks,

Andy

**Comment by psignoret** [comment]
No, username/password is not filled out twice. Username, password, any other authentication factors that may be enabled are only filled out once: in Azure AD. I believe you are looking for the reverse, which is not what this plugin aims to do.

This plugin allows you to SSO *to* WordPress *from* Azure AD. (Keep in mind that signing in to Azure AD is equivalent to signing in to Office 365, Azure AD is the identity system for Office 365.) The *single* time you sign in is with Azure AD.

In OpenID Connect terms, Azure AD is the *OpenID Provider* (OP), and the WordPress installation is the *Relying Party* (RP). The OP is the system that authenticates the users and decides if they're allowed to sign in to the app. The RP is the system that trusts the OP, and uses the information provided by it to identify the signed in user.

What you seem to be looking for (sign in to WordPress, and have that sign-in be recognized by Azure AD--and by extension, Office 365) is not what this plugin intends to do. Azure AD does supports federating authentication to a different Identity Provider. There are other plugins out there that allow WordPress to act as an Identity Provider (such as [miniorange-wp-as-saml-idp](https://wordpress.org/plugins/miniorange-wp-as-saml-idp/)), but I've never tested these and don't know if they would be compatible with Azure AD.

Side note: Regarding "adal.AuthenticationContext and acquire_token_with_username_password". The various flavors of using ADAL to acquire an Access Token by invoking the OAuth 2.0 Resource Owner Password Credentials Grant flow (which is what you're alluding to) do *not* result in anything that you can use to obtain a signed-on session for any Office 365 service, certainly not in a browser.  In fact, there scenarios where this flow is even the least bit recommended are tiny and decreasing. See [this conversation](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482) for some more context.
