### ISSUE TITLE
Possible conflict with Multisite User Sync plugin

### ISSUE THREAD

**Issue by JustinTrouble** [psignoret/aad-sso-wordpress#123]
I just upgraded our working implementation to the latest (commit a3fbc7ec6dba452ee644d88540ad1bd1546c8d20), but it broke authentication.

After signing in to AAD, Chrome says it's `Waiting for <web site url>...` and there is a long pause (much longer than is normal), then a redirect to `wp-login.php?code=...&state=...&session_state=...`, at which point WordPress reports "Oops! That page can’t be found" and the user is not logged in to WordPress.

I've tried different points in the repository, and found that up to and including commit 837286b1cff709c4083abfce3f298f3233c80601 works fine, but with commit fe1129fb8a73f67a691f98d475a2bb3331cd7abc it breaks.

**Comment by psignoret** [comment]
@JustinTrouble Would you mind sharing how you've configured the plugin? Which features are you using? (I assume you're using the Azure AD group to WordPress role feature?)

**Comment by JustinTrouble** [comment]
Hi @psignoret. 

Indeed we are!

Configuration below (placeholder substitutes included):

**Setting** | **Value**
--------|--------
Display name | Web Site Name
Domain hint | Not set
Client ID | xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Client secret | xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Redirect URL | http://www.url.com/wp-login.php
Logout redirect URL | http://www.url.com/wp-login.php
Field to match to UPN | Login Name
Enable auto-provisioning | True
Enable auto-forward to Azure AD | True
Enable Azure AD group to WP role association | True
Default WordPress role if not in Azure AD group | Subscriber
**WordPress role to Azure AD group map** |
**WordPress Role** | **Azure AD Group Object ID**
Administrator | xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Editor | xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Author | xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Contributor | xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Subscriber | xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
OpenID Connect configuration endpoint | https://login.microsoftonline.com/common/.well-known/openid-configuration

**Comment by psignoret** [comment]
@JustinTrouble I can't seem to be able to reproduce this issue. Can you also list any other plugins you have enabled? If you disable the role -> group mapping, does the issue continue?

**Comment by JustinTrouble** [comment]
@psignoret Thanks so much for taking the time to try and reproduce the issue.
Today I've had a good look at all the plugins we have installed, and after a bit of trial and error found that the issue occurs when used with the [Multisite User Sync](https://wordpress.org/plugins/multisite-user-sync/) plugin.
It's a tiny plugin (and despite what the two latest reviews say, it still works for me).

It uses the following hooks:
- wpmu_new_blog
- wpmu_new_user
- _set_user_role_

The users I've tried to login as are only in a single AAD Group (not multiple).

If I disable "Enable Azure AD group to WP role association", then aad-sso-wordpress works fine with Multisite User Sync.

**Comment by psignoret** [comment]
@JustinTrouble Thanks for the details. As you point to, this is quite possibly a conflict in how `multisite-user-sync` hooks into `set_user_role`. (Which is invoked when `aad-sso-wordpress` calls [`WP_User::set_role()`](https://developer.wordpress.org/reference/classes/wp_user/set_role/) with an empty string to clear pre-existing roles before granting the user the roles to which they are entitled from the Azure AD group memberships.) 

I can't tell what the specific conflict is from just glancing at the code for the plugin, so I'll have to dig into this tomorrow.

Can you give me some details on your blog setup? Sounds like you are running with Multisite, correct? Which version of WordPress?

Have you tried disabling all other plugins except `aad-sso-wordpress` and `multisite-user-sync`, to confirm that it is actually `multisite-user-sync` and not a third plugin (e.g. one which hooks into something invoked by `multisite-user-sync`) which is causing the issue?

And for when the issue does present--is this for a pre-existing user? Or for a user which would be provisioned on-the-fly? Or both?

**Comment by JustinTrouble** [comment]
Hi @psignoret,

Yes, a Multisite installation, consisting of 2 sites and 5 users.
It's the latest version of WordPress. So it was 4.7.2, but upgraded to 4.7.3 yesterday.

I mirrored my live site and disabled _all_ plugins except `aad-sso-wordpress` and `multisite-user-sync` and can confirm that it's `multisite-user-sync`.

The issue is present for both existing users, and users which are provisioned on the fly.

**Comment by bradkovach** [comment]
roles are assigned differently on multisite, so it's probably time for `is_multisite()` somewhere.  I can investigate this this weekend.  TBH, though, I haven't worked with WordPress multisite since it was its own standalone distribution.

**Comment by psignoret** [comment]
@JustinTrouble Thanks, I'll use these details to figure out what's going on.

@bradkovach The plugin generally works on multisite, I test every now and then, I just haven't tested since we switched to supporting multiple roles. I'm pretty sure setting a role is still just `WP_User::set_role()` (e.g. L168 in [`add_user_to_blog()`](https://developer.wordpress.org/reference/functions/add_user_to_blog/)).

**Comment by JustinTrouble** [comment]
The [Multisite User Sync](https://wordpress.org/plugins/multisite-user-sync/) plugin has been marked as abandoned by the maintainer, so I'm closing this issue.
