### ISSUE TITLE
Cache Headers set on init 

### ISSUE THREAD

**Issue by stephen-kainos** [psignoret/aad-sso-wordpress#124]
Currently it looks like PHP sessions are being initialised by this plugin on the init hook. (https://github.com/psignoret/aad-sso-wordpress/blob/master/aad-sso-wordpress.php#L475) 

This causes the PHP session cookie, and the Cache-Control headers to be sent with the HTTP response. The problem is that this happens on every request to the WordPress site, even if we aren't authenticating. 

This causes a number of issues with caching servers like Varnish where they can't cache content with cache busting headers. Could register_session be moved to the login_init hook, before save_redirect_and_maybe_bypass_login ?

**Comment by psignoret** [comment]
@stephen-kainos Is this still an issue?
