### ISSUE TITLE
`upn` vs `oid` to uniquely identifying a user

### ISSUE THREAD

**Issue by sudar** [psignoret/aad-sso-wordpress#127]
In the AD instance that I am using, users are added using their Microsoft account. Because of this `upn` is not set for these users.

We have changed the following line to use `oid` instead of `upn`. https://github.com/psignoret/aad-sso-wordpress/blob/master/aad-sso-wordpress.php#L281

I don't fully understand the difference between these two, but would it make sense to check for `upn` and if it is not present in JWT token, then automatically use `oid`?

**Comment by psignoret** [comment]
Actually, it makes much more sense to use `oid` *always* (with adequate error handling if `oid` is not present). If you want to send a pull request with that change, you get the credit. :)

**Comment by ryanwelcher** [comment]
I believe that his has been addressed with this commit?
https://github.com/psignoret/aad-sso-wordpress/commit/07c1e7e0035eca5720af8681eb7e93ec0575f673#diff-a0ada58cb496292a73dad99a8465f94f

**Comment by psignoret** [comment]
Indeed it was, I just didn't close this issue. Thanks!
