### ISSUE TITLE
No Redirect to Azure AD Unable to Login

### ISSUE THREAD

**Issue by richardjgreen** [psignoret/aad-sso-wordpress#130]
Hi there,

I installed this plugin last night and configured it per the instructions. I have the link visible on the /wp-login.php page but when I click the link, nothing happens. The URL looks strange so me as I would be expecting the URL to point to login.microsoftonline.com or such but instead, it's pointing back to my own site?

Here's the link from the /wp-login.php page:
"https://richardjgreen.net/wp-login.php?response_type=code&scope=openid&domain_hint=richardjgreen.net&client_id=c902918b-0a40-4233-bdc9-e43771568707&resource=https%3A%2F%2Fgraph.windows.net&redirect_uri=https%3A%2F%2Frichardjgreen.net%2Fwp-login.php&state=%7BE3927278-E152-4178-9F06-8F48C27D2F07%7D&nonce=%7BE3927278-E152-4178-9F06-8F48C27D2F07%7D"

In the plugin settings, I have configured it to match on Email Address, assign roles based on Azure AD group and entered all the group IDs. No other options are enabled.

Any thoughts anyone?

**Comment by psignoret** [comment]
@richardjgreen, what do you have as the setting in 
**OpenID Connect configuration endpoint**?

**Comment by richardjgreen** [comment]
The OpenID Connect Configuration Endpoint was set correctly, but I found another issue which sorted it.
I had the Application URL in AAD set to /wp-admin/ and not /wp-login.php.

After I updated that it started working a treat. My bad.

**Comment by psignoret** [comment]
Interesting, the app ID URI and the "sign-on URL" in Azure AD do not have any effect on how the "sign in" link is constructed. It's good to know you have it working, though, feel free to reopen if it comes up again.
