### ISSUE TITLE
Error after transferring Azure Client App to new tenant

### ISSUE THREAD

**Issue by woodwardmatt** [psignoret/aad-sso-wordpress#131]
I've been using the plugin for a while now with no issues. I recently had to relocate the client apps in Azure to a new tenant (so had to delete and recreate the apps). I setup them back up exactly the same (with the exception of a non-expiring key). But no joy, I get the following error:

ERROR: Access denied to Azure Active Directory. AADSTS50000: There was an error issuing a token. AADSTS90092: Non-retryable error has occurred. Trace ID: a87a6d24-543e-4063-8d63-d5ad06f45200 Correlation ID: 1f174524-13e9-4e18-9f18-b58e643ef18e Timestamp: 2017-03-30 10:31:54Z

Has anyone else come across this issue? The move has quite clearly caused the issue, as I believe all was working fine before. Just a little stuck :(

**Comment by psignoret** [comment]
Which permissions have you configured the application to request (i.e. in the Azure portal)?
Does your user get prompted for consent when signing in?

**Comment by psignoret** [comment]
Also, how did you register the app? (E.g. classic Azure portal (https://manage.windowsazure.com), Azure portal (https://portal.azure.com), PowerShell (New-AzureADApplication), Graph API)?

**Comment by woodwardmatt** [comment]
Just one permission - read the user profile  & sign in. You do get prompted for credentials correctly and redirected back, then the error is displayed on the WordPress login page.  The app was registered through the Azure portal only.

**Comment by woodwardmatt** [comment]
Ohh and thank you for responding soo quick :) 👍

**Comment by woodwardmatt** [comment]
Some further testing today revealed it has something to do with trying to login with users outside of the tenant that has a custom domain associated with them... Users in the same tenant, or users with an onmicrosoft.com account are able to login just fine.

..Very strange, but definitely an Azure tenancy / permissions related issue. I'll update this thread once I found out the cause, for anyone else that comes across the issue.

**Comment by psignoret** [comment]
@woodwardmatt Are all of the users who are trying to sign in users of the same Azure AD tenant? If there are users who are normally from a different tenant--have they been invited to the main tenant?

**Comment by psignoret** [comment]
@woodwardmatt If you're still experiencing this issue, please feel free to re-open this.

**Comment by woodwardmatt** [comment]
_Side Note_: Users are mostly from external tenants, and the app is setup to be multi-tenant. Users haven't been explicitly invited to our tenant.

Just another update (this has been going on a bit) the underlying issue was related to the old (deleted) client app Id being cached on tenants (and not removed, even though invalid) so when an existing user tried to login with my new app id , there was then a conflict between the app id's being used for authentication and the above error is then thrown. 

No immediate solution being provided by the Azure team on this at the moment, as they are unable to delete the invalid app Id from their customers tenants (and there is no process to remove, or expire, or notify tenant admins). Still waiting to hear if they are able to assist any further on this. 

Just thought I'd share for anyone that comes across the issue too :)

**Comment by psignoret** [comment]
Can you send me an email at philippe.signoret@outlook.com with details about your setup?

**Comment by dineshcooper** [comment]
Experiencing exactly the same issue - was unable to get anywhere with microsoft support. Please do update here if you manage to work out a fix.

**Comment by psignoret** [comment]
@dineshcooper I realize this is a super late response (sorry, I somehow missed the notification for this). Are you still having this issue?

**Comment by woodwardmatt** [comment]
Ok sorry for the long delay between responses. It seems that in this scenario (where there is a conflict between application ID's on the live site and those cached on the user's tenant which they have previously consented to), the application needs to prompt for consent again. 

This needs to be achieved by re-issuing the OpenID Connect Authentication Request with the prompt=consentparameter (as detailed [here](https://azure.microsoft.com/en-us/documentation/articles/active-directory-protocols-openid-connect-code/#send-the-sign-in-request )). 

A couple of suggestions (which are far from ideal, and still under review) made by MS on approaching this are:

1. Add logic that detects an unauthorized action (e.g. a 403 response from an API), and then attempts to re-consent.
2. Add logic (and state) in your application that keeps track of the first time a user uses a feature that requires the new permission. At first use, prompt them for re-consent.
3. Add logic (and state) in your application that keeps track of something along the lines of a "consent version" for each user. When a user signs in with a lower "consent version" than what your application is at, you can immediately send them back to re-consent.

A note from MS: In all cases, be careful not to get in a re-prompt loop--you should control the number of times a user gets sent back to re-consent. It may be the app/user actually doesn't have the required permissions, that your database is down or malfunctioning, etc.

Haven't had time to explore this much further just yet, but thought I would share the feedback from, the MS support teams in case any of you guys get chance to find a way around this with the aad-sso plugin :)

**Comment by woodwardmatt** [comment]
Another late update - I'm still seeing some errors of: 

"ERROR: Access denied to Azure Active Directory. AADSTS65005: Application \'[My Current App ID]\' is requesting permissions that are either invalid or out of date. "

@psignoret Do you think this is related to the above thread or something new / different?
