### ISSUE TITLE
Username and/or Password is empty

### ISSUE THREAD

**Issue by JLags** [psignoret/aad-sso-wordpress#139]
Hi,

I followed your readme but each time I try to login with Azure users it redirects me to O365 login (wich looks good) and then it redirects me to the worpress login with the error "Username and/or Password is empty".

I did the setup like the "Group membership-based roles, default role, auto-provision" example.

Any help would be appreciate :-) 

Best.
J.

**Comment by psignoret** [comment]
That is, indeed, quite strange. Have you tried disabling plugins you have which may have something to do with login? (Or, can you share the list of plugins you're using currently?)

**Comment by JLags** [comment]
Hi,

Thank you for your answer, here is a list of my plugins (activated):
BuddyPress
CB Change Mail Sender
Contact Form 7
DP Pro Event Calendar
DT World Clock
Eonet Live Notifications
Eonet Live Search
File Away
Flamingo
Slider Revolution
Unyson
Wise Chat Pro
WP File Manager

**Comment by JLags** [comment]
I made a fresh setup on another WP with another theme and it works.. So my problem is between the theme and the plugin..

**Comment by bradkovach** [comment]
if you can narrow it down to the plugin, I would gladly investigate the conflict.

**Comment by JLags** [comment]
THe thing is that the theme has it own custom login, here is the answer from WOFFICE:

"Unfortunately there isn't any way coming from Woffice for that. I don't know if exists any WordPress plugin for that, but likely you will need to disable the custom login page of Woffice."

So don't worry, your plugin is just awesome and working, I use it on my personnal WP now :) Thanks.

J.

**Comment by psignoret** [comment]
@JLags, if you can put me in touch with the theme authors, I can work with them to investigate where the conflict is coming from, so that we can address it. Let me know!

**Comment by JLags** [comment]
The theme is Woffice and I can only contact them from here: https://alkaweb.ticksy.com/
