### ISSUE TITLE
Error on 1st sign-in attempt

### ISSUE THREAD

**Issue by viperguynaz** [psignoret/aad-sso-wordpress#144]
getting the error:
`Notice: Undefined index: aadsso_antiforgery-id in D:\home\site\wwwroot\wp-content\plugins\aad-sso-wordpress\aad-sso-wordpress.php on line 239` 

on the 1st attempt, the 2nd attempt logs in fine

**Comment by psignoret** [comment]
@viperguynaz It's been a while since you opened this. Are you still seeing this issue? If you are, can you share the platform you're running WordPress on, and the plugins you're using? Does the issue still present if you disable other plugins?

**Comment by psignoret** [comment]
@viperguynaz I'm going to close this issue for now, but please feel free to reopen it if you're still having issues.
