### ISSUE TITLE
Auto forward but not back button

### ISSUE THREAD

**Issue by ChainsawBaby** [psignoret/aad-sso-wordpress#146]
I'm testing this plugin for a large company, and they want the users to automatically be redirected to the AAD SSO page, and that works.
But on that page, there are no buttons that allows me to click cancel, so I can go back to the old login page, and login with username and password
(we don't have access to their AAD service, only username and password for WP)

![https://i.bratteng.me/yokplO8rWr.png](https://i.bratteng.me/yokplO8rWr.png)

**Comment by psignoret** [comment]
The screenshot you've shared is of the Azure AD sign-in page. This is something controlled entirely in Azure AD, not by this plugin.

If you've looking for a way to occasionally work around the redirect, you can use the `aadsso_no_redirect` URL option described here: https://github.com/psignoret/aad-sso-wordpress#bypassing-automatic-redirect-to-azure-ad-to-prevent-lockouts

Let me know if this addresses your issue.

**Comment by ChainsawBaby** [comment]
Yes!

Didn't see that section. Updated the plugin and tried `aadsso_no_redirect` and it worked like a charm. Doing a minor edit so the security dudes will approve it.
