### ISSUE TITLE
aadsso_no_redirect parameter does not work

### ISSUE THREAD

**Issue by pstidsen** [psignoret/aad-sso-wordpress#149]
Hi,

Even though I set the parameter ?aadsso_no_redirect=please after the login URL, I am redirected to the login page at Microsoft instead of the normal WordPress login page. The issue is the same with all plugins deactivated.

/ Peter

**Comment by asifma** [comment]
Same problem here...

**Comment by psignoret** [comment]
@pstidsen @asifma This was added very recently, in the very latest version of the plugin. Are you using this? If not, you can try `?action=aadsso_no_redirect`, which should have the same effect, even on older versions of the plugin.

**Comment by martensnico** [comment]
Just updated our blog to the latest version, works like a charm, thanks Philippe!

**Comment by psignoret** [comment]
@asifma @pstidsen Feel free to comment or reopen if you are still having any issues.
