### ISSUE TITLE
Availability in wordpress.org plugins directory?

### ISSUE THREAD

**Issue by chris18890** [psignoret/aad-sso-wordpress#150]
Hi all,

I'm really liking this plugin & have successfully deployed it to two of my WordPress instances.

I'd really like to deploy it for some other clients, however I don't have SSH access to the WordPress install, only the admin web interface. Any idea when the plugin will be published in the plugin directory?

**Comment by psignoret** [comment]
As soon as possible. I'm hoping in the next few weeks. I'll update here when it's done.

**Comment by bradkovach** [comment]
Has been discussed in the past... https://github.com/psignoret/aad-sso-wordpress/issues/60

I think everybody is just busy with day jobs/life/etc LOL

**Comment by bradkovach** [comment]
Resources I have found...

https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy
https://github.com/bigbitecreative/paddle
https://gist.github.com/kloon/6487562
https://github.com/abackstrom/wp-whos-online/blob/master/release.sh
