### ISSUE TITLE
Error when checking group membership displayed as "not a member"

### ISSUE THREAD

**Issue by psignoret** [psignoret/aad-sso-wordpress#151]
If there's an error in the Graph API call that checks group membership (e.g. because the app has not been granted the required permissions), the error message just says the user is not a member of the group. Need to add error handling to distinguish between the two cases, and surface actual errors.

Possible reason for #148.

**Comment by jjacobs1** [comment]
I can't seem to get groups membership to work either. Tried everything I can think of. Getting a both "ERROR: AAD user XXXX is not a member of any group granting a role." and "ANTIFORGERY_ID mismatch. Expecting XXXX". If I set the default wordpress role of not in in Azire AD group everything works great, just not groups.

**Comment by psignoret** [comment]
@jjacobs1 Try again with the latest version of the plugin, and following the latest version of the instructions: https://github.com/psignoret/aad-sso-wordpress/issues/148#issuecomment-329805178

Let me know if this fixes the issue.

**Comment by jjacobs1** [comment]
@psignoret You the man! Works like a charm now 🥇
