### ISSUE TITLE
QUESTION: Is it possible to sign-in a user with this code? 

### ISSUE THREAD

**Issue by ikeamster** [psignoret/aad-sso-wordpress#155]
Seems like you cannot pass username password credentials through your own local login form. Redirection is a must cause of the OAUTH2 protocol.

**Comment by psignoret** [comment]
I don't quite understand what you are asking. Could you describe what you would like to do?

**Comment by anormore** [comment]
Correct. To use this plugin you can "Sign in with Office 365". Which redirects to Microsoft login, and comes back to wordpress. This plugin is excellent.

@psignoret This issue can probably be closed.

**Comment by psignoret** [comment]
Agreed, I'll close the issue. @ikeamster, let me know if you still need help.
