### ISSUE TITLE
Asking feature 

### ISSUE THREAD

**Issue by bluejab** [psignoret/aad-sso-wordpress#158]
I am new user that just start a project using this plugin
Is there a way to make a registration page in wp that can automatically create an azure account after you create an account in wp using this plugin function? 

Sorry if this make no sense or this is a wrong place to ask

Thank you before

**Comment by bradkovach** [comment]
This is a little out of scope for our plugin; our intent is to allow robust authentication using Azure Active Directory as the authoritative authentication mechanism.

**Comment by bluejab** [comment]
Okay
Thank you for your respon 
If so do you know any plugin that have that kind of use? 
Or we have to build a new one from scratch?

**Comment by psignoret** [comment]
It depends on your use case. This plugin is primarily oriented for members of an organisation to sign in to a WordPress site. Most organizations have an existing onboarding process for new users (anything from manual user creation in the Office 365 portal to automatic synchronisation from an on-premises directory solution or from an HR application), which will result in a user account in Azure AD which can then be used to sign in with this plugin.

If this is your scenario, and you're looking for signed-in user (e.g. a admin of your org) to be able to create users from the WordPress site/control panel, it would not be difficult to create a simple plugin that complements this one, which would use the access token obtained for the signed-in user, and call the Microsoft Graph API to create a new user in Azure AD (and create the corresponding user in WordPress).

If, instead, you are looking to target users from the general public (not necessarily users who already exist using their work or school account), then a better approach would be to use Azure AD B2C (business to consumer). Azure AD B2C Can integrate both sign up (i.e. register) and sign in user journeys easily. Microsoft has released (with as-is caveats) a plugin that is focused on this scenario: https://github.com/AzureAD/active-directory-b2c-wordpress-plugin-openidconnect. It's a bit rough around the edges still, but don't hesitate to submit issues, I'm sure the maintainers will respond. :)

**Comment by bluejab** [comment]
Thank you for your suggestion
Yeah my scenario is the second one
I will go and check it out 
And i am gonna ask do this plugin do store a token that it receive after we login if yes how can i retrieve it?
