### ISSUE TITLE
Unable to Logout from WordPress from WordPress logout link

### ISSUE THREAD

**Issue by vanxy** [psignoret/aad-sso-wordpress#163]
Hi,

I have successfully connected our WP with Azure AD (login will be redirected to Azure login screen) and I can login with my AD account.
Problem is, when I click the Logout link from the WP installation (url is something like mysite.com/wp-login.php?actionlogout&_wpnonce=XXXXXXXXXXXX&redirect_to=https%3A%2F%2Fmysite.com%2Fwp-admin%2F%3Floggedout%3Dtrue ), I am not logged out. I am still redirected to wp-admin dashboard.

Btw, I am using the minimal setting only.

Is there anything I need to set?
Appreciate your kind advices

Thank you

**Comment by psignoret** [comment]
Do you have any other plugins that are in any way related to login or logout? What version of WP?

**Comment by vanxy** [comment]
Hi

I am using WP 4.9.1. I only have Single Sign-on with Azure Active Directory plugin activated that is related to login/logout.
Other plugins I activated are bbPress, Wordfence Security, CF7

Thank you

**Comment by vinhtvu2** [comment]
I'm also having this issue. After clicking logged out, if I go to the WP-admin page or any other page, it'll still show that I'm logged in. The only way to truly log out is to clear cache and close browser and open new browser. So the logout function doesn't remove cookies or getting rid of the persistent token. On Outlook 365, it shows a "logging you out of Microsoft" screen. 

So there has to be a call to that after the WordPress logout has been clicked.

https://login.windows.net/{tenantid or "common"}/oauth2/logout?post_logout_redirect_uri={URL}

I tested by adding my tenantid and the redirect url that's in the reply URL and it worked to log me out.

**Comment by psignoret** [comment]
It sounds like you are expecting that a "log out" of WordPress should also trigger a full sign-out from Azure AD (which, like you've observed, it _not_ what this plugin is currently designed to do). Is that the behavior you're expecting?

**Comment by vinhtvu2** [comment]
I think if people use the plugin, and want persistent sessions, they could just close the browser. When they open it back up, the session should still be there because of the ticket. But if they deliberately click the logout button to log out, it should terminate the session and log out of Azure AD? For instance, using someone else's computer, or testing a different account. I would log out afterward. The expected behavior would be to clear all trace of my authentication.

That's just my logic of course.

**Comment by psignoret** [comment]
That's good feedback. I've gotten mixed responses to this in the past: some want it to only clear the WordPress session but not the Azure AD session. Others, like you, expect both to be signed out. I think the best solution here is just to make it configurable.

**Comment by vinhtvu2** [comment]
Definitely more flexible and cater to the mass by making it configurable.

**Comment by vanxy** [comment]
Thanks @vinhtvu2 @psignoret 
I did implement the same solution as @vinhtvu2  mentioned.
In my case, we would like to have the Logout from AD as we have few people sharing one PC, or if they access the site outside of the corporate network.

I think it would be helpful if it's configurable. But for now, we are good.
 
Thanks again.

**Comment by psignoret** [comment]
@vanxy @vinhtvu2 This is now a configurable option in the latest version. Thanks for your feedback!
