### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by flpmilan** [psignoret/aad-sso-wordpress#164]
I got this error every time, when try to authenticate on login screen:

**ERROR: Invalid id_token. OpenSSL unable to verify data: error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01**

Any idea? The key is correct, checked it multiple times.

**Comment by psignoret** [comment]
Can you elaborate on what you mean by the key being correct? How are you deciding that?

**Comment by psignoret** [comment]
@flpmilan I'm going to close this issue for now, but please feel free to comment or open another issue if you're still having this problem.
