### ISSUE TITLE
Bypass Login account with special link

### ISSUE THREAD

**Issue by vinhtvu2** [psignoret/aad-sso-wordpress#166]
Our current configuration:
Enable auto-provisioning = True
Enable auto-forward to Azure AD = True
Enable Azure AD group to WP role association = False

WordPress version: 4.9.2
aad-sso-wordpress vesion: Version 0.6.2

I'm wondering if it's possible to add an option, so that we can have a secret URL that we can access to login using a local user in case AAD is down / inaccessible for whatever reason.

Like adding a specific url field that can be set, then redirecting that to the login page which accept local logins?

Thanks, great plugin so far!

**Comment by psignoret** [comment]
Have you had a look at this section of the README? https://github.com/psignoret/aad-sso-wordpress#bypassing-automatic-redirect-to-azure-ad-to-prevent-lockouts

**Comment by vinhtvu2** [comment]
Well I feel like an idiot...
Thanks!

**Comment by psignoret** [comment]
No worries! :) 

(Pro tip: Though the documented approach is the safest way to skip the redirect, putting ?action=whatever will actually have the same effect.)
