### ISSUE TITLE
Help on your plugin

### ISSUE THREAD

**Issue by kmnathancse** [psignoret/aad-sso-wordpress#170]
Hi Sir,

My wordpress site is in root directory.  So anybody having the URL can access my site.

I have used your plugin to auth against AD. It is perfectly working when i click a URL under wp-admin login page . Means only when i explicitly type mysitename/wp-admin, URL. my problem here is i do not want any one access the website without login to Azure AD.

How do i restrict my site only uses your plugin URL and load the site.

Flow

1. www.testintranet.com - > currently loads for any users
2. www.testintranet.com/wp-admin - Login page shows and there is a link to launch the office 365 URL.
3. When i click that, i am able to give my office 365 username and password and then it loads my page perfectly.
4. In Azure ADD app registration home page and reply URL is www.testintranet.com .

Please give me a solution, when my users type www.testintranet.com it should redirect to office 365 plugin URL and after it is done it should load www.testintranet.com . or provide options how to achieve it

**Comment by psignoret** [comment]
This plugin does not currently do anything to decide _when_ a user must sign in, it only adds a new method for _how_ the user can sign in.

There are several other plugins out which you can use to require that access to all parts of your site (or only certain parts) require the user to sign in. Here are a few examples I found by searching for "wordpress require login": [Force Login](https://wordpress.org/plugins/wp-force-login/), [Simple Require Login](https://wordpress.org/plugins/simple-require-login/), [wp-require-login](https://wordpress.org/plugins/simple-require-login/).

If you're using, for example, Force Login to require all access to be from signed-in users, then you can simply configure this plugin to auto-redirect to Azure AD for sign in (it's one of the configuration options), and you will get the behavior you're looking for.
