### ISSUE TITLE
Any way to check against a single group to grant membership?

### ISSUE THREAD

**Issue by brandontravis** [psignoret/aad-sso-wordpress#177]
Rather than mapping roles for all different user roles, is there simply any way to check against a single group to provide access before the WP User is created?

**Comment by psignoret** [comment]
@brandontravis This would not be very difficult to add, but is not available today.

If you have Azure AD Premium (e.g. because you have an Enterprise Mobility + Security (EMS) subscription), then you can do this at Azure AD. (Let me know if you want instructions.)

**Comment by brandontravis** [comment]
So, this was actually fairly simple ... I just created a new role with no capabilities (the same thing that happens when you select the "No role for this site") from the user settings page. 

Can close this issue, as I Achieved effectively the same thing.
