### ISSUE TITLE
Add checkbox to dis/enable AD group to role mapping in wp-admin

### ISSUE THREAD

**Issue by blobaugh** [psignoret/aad-sso-wordpress#20]
Right now mapping the authenticating user's AD group to a WP role is enabled by default and can only be changed by altering the plugin at runtime. We should add in a checkbox to the settings page in wp-admin to dis/enable mapping easily by the site admin.

**Comment by jtsternberg** [comment]
I think we're good here. I've also added a dropdown setting for selecting the default fallback role: https://github.com/WebDevStudios/aad-sso-wordpress/commit/de2ffc1ab8c03d0fdec22029636a87274f93097f
