### ISSUE TITLE
Error when signing in - "Session does not contain antiforgery ID."

### ISSUE THREAD

**Issue by chris18890** [psignoret/aad-sso-wordpress#200]
Hi all,

websites https://belfasttechservices.co.uk & https://hampshiretechservices.co.uk

Having recently updated to v0.6.5 (from 0.6.4) of the plugin on both sites I've started getting the following error message when trying to sign in - "Session does not contain antiforgery ID." this seems to happen both when clickign the log in link under the meta section of the homepage & aswell as browsing to https://<site-url>.co.uk/wp-admin

I've set up the plugin following the settings in the readme, additionally setting the domain hint & allowing "Match on alias of the UPN". I went as far as to deactivate & delete the old plug in from wordpress & redownbload a fresh copy from GitHub, as well as delete the old app registration in AAD & set up a new one.

Running the latest version of wordpress (4.9.7) on ubuntu 18.04 with latest Apache/MySQL/PHP stack.

Everyhting else seems to be functional, just the signing with SSO...

**Comment by chris18890** [comment]
Just running it off a single server. I'd rebuilt it with 18.04 & had set everything up again & it was working, this seems to be a recent issue, & was also happening in 0.6.2. No major changes other than allowing wordpress & Jetpack to be upgraded; though JetPack SSO seems to have broken recently as well...

**Comment by chris18890** [comment]
Didn't make any changes, just installed the latest versions with APT, so unless something's changed in the release versionf ro 18.04 vs 16.04? will do soem testing & rebuild on both distros to see if there's any difference :)

**Comment by volupheles** [comment]
I've just tried this plugin for the first time and getting the same error. Running it on a windows IIS server. WordPress install is pretty much new.

**Comment by volupheles** [comment]
An update for any users with IIS issues on this. Make sure PHP can write to the temp directory. In your php.ini file, look for session.save_path =
Setting this to a writable directory fixed my issue.

**Comment by psignoret** [comment]
@volupheles  Sorry for the delayed response here, though I'm happy to see you discovered the issue. PHP sessions must be enabled on the server hosting the site for this plugin to work.

**Comment by farmerchris** [comment]
I had this problem on an Ubuntu server.  We traced the cause: the disk was full.  Because it could not create new files in the session directory, it could not save the session contents.  Just wanted to record this for the next person who Googles this error message (which could be me again).

**Comment by stefanie-sidekick** [comment]
I'm experiencing the same problem after transferring the website to a new hosting. But I already deleted my app registration in Azure Active Directory and created a new one.
