### ISSUE TITLE
ERROR: Unable to check group membership in Azure AD: Request_BadRequest.

### ISSUE THREAD

**Issue by d0brii** [psignoret/aad-sso-wordpress#206]
Hi, 
When I'm trying to login with  "Enable Azure AD group to WP role association" turned on I'm getting: 

ERROR: Unable to check group membership in Azure AD: Request_BadRequest.

Any help would be appreciated :). 

Thank You.

**Comment by psignoret** [comment]
Did this suddenly stop working, or did it never work?

What did you use as the values for the group's?

Can you confirm you granted the necessary permission in Azure AD?

**Comment by d0brii** [comment]
Hi There,
Thank you for the quick response :)
It is a brand new install, and from the first run had above error. 
If I disable  "Enable Azure AD group to WP role association" Azure AD user can log in with granted permissions of the contributor.
Regarding necessary permissions in Azure AD, I followed provided instructions. 
Regarding settings here is relevant output from debugger;

....
'match_on_upn_alias' => true,
   'enable_auto_provisioning' => true,
   'enable_auto_forward_to_aad' => false,
   'enable_aad_group_to_wp_role' => true,
   'aad_group_to_wp_role_map' => array (
    'AllStaff' => 'allstaff',
  ),.......
'graph_endpoint' => 'https://graph.windows.net',
   'graph_version' => '1.6',

**Comment by d0brii** [comment]
Thank You! It’s working now :)
