### ISSUE TITLE
Error after moving site to 'www.'

### ISSUE THREAD

**Issue by hobn1354** [psignoret/aad-sso-wordpress#211]
I just moved my site and its URLs to 'www.domain.org' from 'domain.org'
This was necessary due to other reasons...

After having changed the WP url/site urls in the database and used the Velvet Blues plugin to update links, I added code in the .htaccess file, to force/redirect access with 'www.'

Then, after trying to logon with AAD SSO, I recieved the following error in the login.microsoftonline.com page:
```
Sorry, but we’re having trouble with signing you in.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'a-string-of-letters-and-numbers-here'.
```
This was continuous and occured on more than one device, so I deleted the Enterprise Application and App Registration in Azure, and went ahead to make a new one WITH the www. prefix. After changing relevant settings and keys back in the WP plugin settings, I tried again to login. I still recieve the same error.

The reply URLs i have on azure are:
- https://domain.org/
- https://domain.org/wp-login.php
- https://www.domain.org/
- https://www.domain.org/wp-login.php

Also, I changed the Logout redirect URL in WP settings to 'https://domain.org', as I had this set up before, but I forgot how to properly set it up in Azure (hence why there are some reply urls without wp-login). I don't know if I have done that part right.

Anyway, my main problem is the error received upon login to AAD, preventing SSO login to WP...

I would be so grateful if anyone could help. Thanks.

**Comment by filipliwinski** [comment]
What is the value of `redirect_uri` in the auth request url (the page you get the error)? Is it correct?

`https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&scope=openid&domain_hint=&client_id=<<appId>>&resource=https%3A%2F%2Fgraph.windows.net&redirect_uri=<<appRedirectUri>>&state=<<state>>&nonce=<<nonce>>`

**Comment by hobn1354** [comment]
Hi, I looked and it seems that the url reply_uri is http://domain.org/wp-login.php

(no HTTPS which is strange??)

However I believe that this IS set as a reply url in azure. I will double check.


Thanks for your help.

**Comment by hobn1354** [comment]
So I added the reply url with HTTP, and there is now no error on the microsoftonline login, however it now takes me back to the wp-login.php page, with the following error:


`ANTIFORGERY_ID mismatch. Expecting 
`

**and then it says nothing???

**Comment by filipliwinski** [comment]
What reply URLs are set in the Azure Portal?

**Comment by hobn1354** [comment]
![20190222_113945](https://user-images.githubusercontent.com/47871013/53240524-d0590500-3696-11e9-9dff-21a71cf730aa.jpg)
![screenshot_20190222-114405_chrome](https://user-images.githubusercontent.com/47871013/53240663-3b0a4080-3697-11e9-8de4-fd2a3b44bb4a.jpg)
I just presser set default on redirect url and it changed it, so I'm going to try again

**Comment by hobn1354** [comment]
it still doesn't work

**Comment by filipliwinski** [comment]
What is the point to have all these reply URLs set in the Azure Portal?

`https://example.com/wp-login.php` should be provided only. That is the value form plugin configuration.

**Comment by hobn1354** [comment]
Oh I set all of them when trying to get it to work :-)

I will clean it up...

**Comment by hobn1354** [comment]
I cleaned it up but it still doesn't work. This is the error I recieve:
![screenshot_20190222-121431_chrome](https://user-images.githubusercontent.com/47871013/53242017-7149bf00-369b-11e9-8dad-3d482b361554.jpg)

**Comment by filipliwinski** [comment]
This issue may be caused by some plugin. See [#65](https://github.com/psignoret/aad-sso-wordpress/issues/65).

**Comment by hobn1354** [comment]
I'll look into it, but I have not added any plugins or done anything like that, only updates. SSO worked fine before I added the www requirement, so I don't know if this is the cause...
