### ISSUE TITLE
Invalid id_token

### ISSUE THREAD

**Issue by pstidsen** [psignoret/aad-sso-wordpress#216]
Hi there,

I am experiencing the same issue as in issue #164. I have configured the plugin according to readme. I get this error:
ERROR: Invalid id_token. OpenSSL unable to verify data: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding

The issue still persist with all plugins disabled and twenty seventeen theme activated.

What is wrong?

**Comment by pstidsen** [comment]
Solution: The app was registered under the "Enterprise applications"-blade in Azure which does not work with the https://github.com/psignoret/aad-sso-wordpress plugin. The app should be registered under the "App registrations"-blade or the "App registrations (Preview)"-blade in Azure.

**Comment by juvinious** [comment]
Hi, ran into this issue as well today.
We are using an enterprise AD application.
Turns out the solution for me was a datetime mismatch as the server was a few minutes behind.
Ran an update with ntpdate to bring it up to speed and the invalid_token issue went away.
