### ISSUE TITLE
Ensure the proper WP login hooks are being called

### ISSUE THREAD

**Issue by blobaugh** [psignoret/aad-sso-wordpress#22]
We need to ensure the proper login hooks for WordPress are being called. This is so security and logging plugins continue to work as expected.

**Comment by jtsternberg** [comment]
This should already be the case since the plugin uses the 'authenticate' filter, right? https://github.com/WordPress/WordPress/blob/master/wp-includes/user.php#L79-L101

**Comment by psignoret** [comment]
According to me, this is already the case.

Closing the issues (as it's ~1 year old), but let me know if you think it should be re-visited.
