### ISSUE TITLE
"Legacy" Application Registration process deprecated as of May 2019

### ISSUE THREAD

**Issue by bradkovach** [psignoret/aad-sso-wordpress#220]
New registration instructions are needed for the application registration process.  MSFT/Azure have disabled the "Legacy" app registration, causing logins to fail.

**Comment by tibricel** [comment]
Just noticed that the other day that Azure was retiring the now Legacy app registration. I haven't tried the new app and I doubt it will work the same way.

**Comment by JJGriffin** [comment]
Thanks for sharing @tibricel, those instructions worked a treat for me!

**Comment by bradkovach** [comment]
@psignoret are these permissions proper?

BK
(i)

________________________________
