### ISSUE TITLE
Redirect Not Working

### ISSUE THREAD

**Issue by jbpatelgit** [psignoret/aad-sso-wordpress#223]
Is this plug-in only works to for admin user to use AD authentication? 

I need the blog to be only accessible for viewing by AAD users. I configured it using instructions but it doesn't authenticate user when I go directly to https://myblog.azurewebsites.net/. It looks like anonymous login is enabled and I am not sure if we are supposed to turn it off or not.

**Comment by psignoret** [comment]
This plugin does not make your blog require sign-in. If you want to disable anonymous access to your blog, you would need to enforce that with a separate plugin (there are a bunch of them).
