### ISSUE TITLE
Webhosting requirements?

### ISSUE THREAD

**Issue by Jelmerkeij** [psignoret/aad-sso-wordpress#226]
Thanks for this plugin. Are there any (minimum) requirements to consider on the webserver? The thing is it works on my test webserver, but on my clients webserver it sometimes works but often get an "Invalid jwks URI" or "Unknown error occured".

I'm testing the same App on both webhosts (with the redirect URI changed depending on which URL we're testing).

**Comment by psignoret** [comment]
Sorry for the late response here. Can you confirm which version of the plugin you're using, and when exactly you get that error message?

**Comment by Jelmerkeij** [comment]
Sorry, I missed your reply. Thanks for getting back to me. I'm using the latest version of the plugin but also found out what the problem was.  The `wp_remote_get` and `wp_remote_post` function were timing out. Passing `[ 'timeout' => 60 ]` as arguments to those functions fixed this specific part of the problem.

I've got it working now, it was a combination of the timeout, session not starting properly and a rights issue.
