### ISSUE TITLE
After logging in, users are directed to wp-admin/profile.php instead of the referring page

### ISSUE THREAD

**Issue by iouri-s** [psignoret/aad-sso-wordpress#24]
I created a WP website
Added "restricted site access" plug-in
Added "aad sso wordpress" login

I can successfully log in now with AAD credentials; however, every time I log in, I get redirected to the profile page. This is not the case when I log in with WP credentials - I get directed to the home page.

**Comment by jtsternberg** [comment]
This is solved in this commit (in our fork): https://github.com/WebDevStudios/aad-sso-wordpress/commit/7f4c55b8ca82dcf01f76a30ebd390c086029bfb1

**Comment by psignoret** [comment]
Thanks @jtsternberg. I'll cherry-pick this one tonight.

**Comment by jtsternberg** [comment]
Also, https://github.com/WebDevStudios/aad-sso-wordpress/commit/fd430c74a543a36113be0da3aa4dde5331235860
