### ISSUE TITLE
href login not working

### ISSUE THREAD

**Issue by rogerol182** [psignoret/aad-sso-wordpress#242]
I install the plugin in wordpress 5.7.1 with php 7.1.6 but the href login "Sign in with your App account" never refresh the url to https://login.microsoftonline.com/common/oauth2/authorize?response_type always be in https://localhost/wp-login.php?response_type.

You Know why?. 

can u help me.

**Comment by psignoret** [comment]
¿Me podría compartir algunos detalles de cómo ha configurado el plugin? ¿Cuales opciones ha cofigurado?

**Comment by psignoret** [comment]
@rogerol182 

I'm closing this issue as I have not received a response. Please feel free to open a new issue if you're still having issues.

Voy a cerrar este "issue" dado que no he recibido respuesta. Si tiene otra pregunta or problema, por favor no dude en crear otra preguta.
