### ISSUE TITLE
after logout user's role in WP gets changed

### ISSUE THREAD

**Issue by hschroda** [psignoret/aad-sso-wordpress#25]
logging out successfully changes the role of the given user in WP to "none"

**Comment by psignoret** [comment]
I wasn't able to reproduce. Here's what I tried:

1. Configured plugin to require specific group memberships to grant roles and sign in.
2. Logged in with AAD.
3. Verified that user had the correct role.
4. Logged out.
5. Logged in to same user, but this time using WP login form.
6. Verified that user still had same role.

If you can still repro, can you share your settings?
