### ISSUE TITLE
Is this repository active?

### ISSUE THREAD

**Issue by hkusulja** [psignoret/aad-sso-wordpress#250]
Hello,
it seems that this repository is not active and now response from the author / owner for more than 2 years.
@psignoret please mark this repo as archived so we know there is no any active development, support, pull request revision etc on this project.

Thank you,
Kind regards

**Comment by psignoret** [comment]
Yes, this repository is active. The plugin works and I review and respond to most issues, as time allows. Thanks for your suggestion!

**Comment by hkusulja** [comment]
fair enough, i just do not see any code updates more than 2 years.
Since it is active and working, thank you for spending your free time on this.
