### ISSUE TITLE
Retirement of basic authentication

### ISSUE THREAD

**Issue by clarm060** [psignoret/aad-sso-wordpress#253]
First I love your plugin! Saves me so much time! I am a Microsoft partner and today they sent us a email about the retirement of basic authentication in apps for Azure, is there a plan to switch to certificate based authentication?

Below is a snippet from thier email.
"If your organization is currently using "Basic authentication" for application access, you will need to migrate to certificate-based authentication prior to mid-February."

Thanks again for all your hard work on this plugin!

**Comment by psignoret** [comment]
This plugin does not use Basic authentication.

**Comment by clarm060** [comment]
sweet thanks for the update :)
