### ISSUE TITLE
Authorization_RequestDenied error when trying to see if user is in a mapped role (document required app permission settings)

### ISSUE THREAD

**Issue by jtsternberg** [psignoret/aad-sso-wordpress#26]
request to `AADSSO_GraphHelper::userCheckMemberGroups()` returns this error:
```
stdClass Object
    (
        [odata.error] => stdClass Object
            (
                [code] => Authorization_RequestDenied
                [message] => stdClass Object
                    (
                        [lang] => en
                        [value] => Insufficient privileges to complete the operation.
                    )

            )

    )
```

Which means there's no way to properly map a user. Do you know the reason for this?

**Comment by psignoret** [comment]
Check the permissions for the application. Should have Delegated Permission to "Read Directory Data" and "Enable sign-on and read users' profiles". README needs an update.

![image](https://cloud.githubusercontent.com/assets/231140/6990496/fcf02fb0-da21-11e4-9d60-1e6e2fd2cef1.png)

**Comment by jtsternberg** [comment]
That did it. Thank you.

**Comment by jtsternberg** [comment]
README updated here: https://github.com/WebDevStudios/aad-sso-wordpress/commit/0f5c73b5b40aa8753683cd828cf82fd2f1ed488d
