### ISSUE TITLE
You do not have permission to view this directory or page.

### ISSUE THREAD

**Issue by norehman** [psignoret/aad-sso-wordpress#260]
I have tried to follow the instructions and set it up but I cannot get past this error when I sign in "You do not have permission to view this directory or page.".

We are hosted via Plesk on a Windows-based VPS. It's a brand new vanilla install of WordPress with only this plugin installed. I have verified permissions in Azure and they are set correctly Graph is configured with the standard required delegated access and I also tried it with the permission to read groups following the instructions.

The redirect URI is the same on both Azure and WordPress I am simply trying the basics to test the functionality but either way when I press the Login option it takes me to the Microsoft Azure page then redirects to the base wp-login.php page with loads of random characters on the end. 

I have set it to provision accounts and not provision accounts and I've configured it to set the role as a subscriber by default but still no luck.

I'm not sure what I'm doing wrong but could do with some advice on how I get it to work.

**Comment by psignoret** [comment]
When do you get the error, exactly? Following the redirect to wp-login.php (with the "random characters" at the end)? What version of WordPress are you using?

**Comment by norehman** [comment]
When I press the login button it redirects to the Microsoft page then it redirects me back to /wp-login.php?code= 

I am using a brand new WordPress install - 6.1.1

**Comment by norehman** [comment]
Upon signing into the Microsoft page, it redirects immediately to the /wp-login.php page. Here is the error:
`
![Screenshot 2023-02-03 150859](https://user-images.githubusercontent.com/104310290/216637765-3312edfb-476f-488a-a2da-10bf393255a2.png)

**Comment by psignoret** [comment]
I'm unable to reproduce the issue as you've described it, I just tried with a fresh WordPress install and fresh download of the plugin.

Can you confirm the following (replace "www.example.com" with your domain):
 - Your WordPress installation is accessible at "https://www.example.com"
 - The regular login page (username/password) is accessible at https://www.example.com/wp-login.php
 - The redirect URL configured for the plugin and in the app registration in Azure AD is https://www.example.com/wp-login.php

**Comment by norehman** [comment]
Apologies for the lack of response. The issue was resolved. I created a new hosting plan and tested it away from our VPS and was able to confirm the issue was related to our Windows-based host and file permissions.

**Comment by psignoret** [comment]
Sounds good, thanks for following up!
