### ISSUE TITLE
Deprecation notice in PHP 8.1/8.2

### ISSUE THREAD

**Issue by Ahmis** [psignoret/aad-sso-wordpress#266]
Hello!

It seems that version 0.7.0 of the plugin gives following PHP notice if website's PHP version is 8.1. or greater. Can you please take a look and fix this in the plugin's code:

PHP Deprecated:  Implicit conversion from float 191.78 to int loses precision in /plugins/aad-sso-wordpress/aad-sso-wordpress.php on line 730

**Comment by Benzamp** [comment]
Also seeing this issue. Deprecated: Implicit conversion from float 4708.09 to int loses precision in /var/www/html/wp-content/plugins/aad-sso-wordpress/aad-sso-wordpress.php on line 724.

**Comment by Benzamp** [comment]
Looks like the error is in the function com_create_guid().

**Comment by Benzamp** [comment]
Looks like the error is in the function com_create_guid().

**Comment by Benzamp** [comment]
@Ahmis make sure your plugin is updated before updating wordpress. Working for me now.

**Comment by psignoret** [comment]
@Ahmis What @Benzamp says. This was fixed a couple years ago, though the version number didn't get bumped.

**Comment by Ahmis** [comment]
Ok thanks! It could be a good practice to bumb the version including this fix. I tried to remove the plugin and add it back via Composer and still I get the version without the fix. If I copy and paste the fix there manually the error goes away.

**Comment by Ahmis** [comment]
I ran composer remove psignoret/aad-sso-wordpress and then added it back with composer require.
