### ISSUE TITLE
ANTIFORGERY_ID mismatch. Expecting 

### ISSUE THREAD

**Issue by hkusulja** [psignoret/aad-sso-wordpress#29]
I have setup latest stable wordpress on blank cPanel server and created Azure AD as your instructions.
I have setup successfully about 7 sites, but two of them are not working.
I have tried replacing your wp-plugin, and recreating in Azure AD side, however no success.

The error after login is on wp-login.php form showing error: ANTIFORGERY_ID mismatch. Expecting 
without any ID.

What can be the issue ? how can I clean and place again your plugin without any cache, cookies or smth, please give me more to troubleshoot, otherwise its a bug error.

my Settings.json same for all sites (different url and IDs of course):

      {
        "org_display_name": "My company site",

        "client_id":        "66cec22g-ac19-4201-acbd-73e4477f8bc8",
        "client_secret":    "D8Nk3tTiU2cMfiNHh4VwPJ7jfQ49BsCBDc05xaUZ4QM=",

        "field_to_match_to_upn": "email",
        "enable_auto_provisioning": true,

        "enable_aad_group_to_wp_role": true,
        "default_wp_role": null,
        "aad_group_to_wp_role_map": {
                "21e0165b-085e-4z4b-a965-e7bfed9deef0": "administrator"
        }
     }

**Comment by psignoret** [comment]
Since this was open so long ago, I'm closing this issue, but feel free to open it again if you're still experiencing a problem with the latest version of the plugin.

**IMPORTANT**: *Never* share the `client_secret` of an application in any public forum. As the name implies, this is a secret, and would allow anyone with access to it to impersonate your application. You should remove this key and create a new one (you can do this from the Azure portal).

**Comment by hkusulja** [comment]
Ok, you can close this case, the client_secret was just a example, it is not an correct one.

However, problem happens sometimes, but sometimes it simply needs time from azure AD to update the group membership and/or those stuff, so it is MS AzureAD fault why this was happening.

You can leave this closed, thank you

**Comment by psignoret** [comment]
Good to know that wasn't the real secret. :)

Changes to Azure AD generally propagate internally quite quickly (within seconds). If the changes are being synchronized from on-premises (e.g. using Azure AD Connect), then there are additional delays until the sync cycle takes place.
