### ISSUE TITLE
Did everything

### ISSUE THREAD

**Issue by unitedspectrums** [psignoret/aad-sso-wordpress#33]
Hello,

I did everything and now when i am at the /wp-admin i try and log in with my active directory login and then it just gives the normal wordpress failed password.

**Comment by psignoret** [comment]
When you go to /wp-admin, do you see a link saying "Sign in with you <organization> account"?

**Comment by unitedspectrums** [comment]
No

Andrew Mathews
Chief Executive Officer
(800) 661-7341 Ext. 5338<tel:(800)%20661-7341;5338>
Mon-Fri 9AM-5PM
www.UnitedSpectrums.com<http://www.unitedspectrums.com>

Manage your account today at

HTTPS://untdsp.com/manage/

Let us know how we're doing email feedback@unitedspectrums.com<mailto:feedback@unitedspectrums.com>

Follow us on social media.

www.facebook.com/UnitedSpectrums<http://www.facebook.com/UnitedSpectrums>
www.twitter.com/UnitedSpectrums<http://www.twitter.com/UnitedSpectrums>

EMPLOYEE ID: 1457320

All calls perform by a United Spectrums employee are recorded for quality assurance purposes.




On Tue, Nov 24, 2015 at 8:26 AM -0800, "Philippe Signoret" <notifications@github.com<mailto:notifications@github.com>> wrote:


When you go to /wp-admin, do you see a link saying "Sign in with you account"?

-
Reply to this email directly or view it on GitHub<https://github.com/psignoret/aad-sso-wordpress/issues/33#issuecomment-159322492>.

Note: Privileged/Confidential information may be contained in this message and may be subject to legal privilege. Access to this e-mail by anyone other than the intended is unauthorized. If you are not the intended recipient (or responsible for delivery of the message to such person), you may not use, copy, distribute or deliver to anyone this message (or any part of its contents ) or take any action in reliance on it. In such case, you should destroy this message, and notify us immediately. If you have received this email in error, please notify us immediately by e-mail or telephone and delete the e-mail from any computer. If you or your employer does not consent to internet e-mail messages of this kind, please notify us immediately. All reasonable precautions have been taken to ensure no viruses are present in this e-mail. As our company cannot accept responsibility for any loss or damage arising from the use of this e-mail or attachments we recommend that you subject these to your virus checking procedures prior to use. The views, opinions, conclusions and other informations expressed in this electronic mail are not given or endorsed by the company unless otherwise indicated by an authorized representative independent of this message
Note: Privileged/Confidential information may be contained in this message and may be subject to legal privilege. Access to this e-mail by anyone other than the intended is unauthorized. If you are not the intended recipient (or responsible for delivery of the message to such person), you may not use, copy, distribute or deliver to anyone this message (or any part of its contents ) or take any action in reliance on it. In such case, you should destroy this message, and notify us immediately. If you have received this email in error, please notify us immediately by e-mail or telephone and delete the e-mail from any computer. If you or your employer does not consent to internet e-mail messages of this kind, please notify us immediately. All reasonable precautions have been taken to ensure no viruses are present in this e-mail. As our company cannot accept responsibility for any loss or damage arising from the use of this e-mail or attachments we recommend that you subject these to your virus checking procedures prior to use. The views, opinions, conclusions and other informations expressed in this electronic mail are not given or endorsed by the company unless otherwise indicated by an authorized representative independent of this message

**Comment by psignoret** [comment]
Did you activate the plugin?

**Comment by unitedspectrums** [comment]
It doesn't show up in wp admin I can only see it in file viewer

Andrew Mathews
Chief Executive Officer
(800) 661-7341 Ext. 5338<tel:(800)%20661-7341;5338>
Mon-Fri 9AM-5PM
www.UnitedSpectrums.com<http://www.unitedspectrums.com>

Manage your account today at

HTTPS://untdsp.com/manage/

Let us know how we're doing email feedback@unitedspectrums.com<mailto:feedback@unitedspectrums.com>

Follow us on social media.

www.facebook.com/UnitedSpectrums<http://www.facebook.com/UnitedSpectrums>
www.twitter.com/UnitedSpectrums<http://www.twitter.com/UnitedSpectrums>

EMPLOYEE ID: 1457320

All calls perform by a United Spectrums employee are recorded for quality assurance purposes.




On Tue, Nov 24, 2015 at 8:31 AM -0800, "Philippe Signoret" <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you activate the plugin?

-
Reply to this email directly or view it on GitHub<https://github.com/psignoret/aad-sso-wordpress/issues/33#issuecomment-159325461>.

Note: Privileged/Confidential information may be contained in this message and may be subject to legal privilege. Access to this e-mail by anyone other than the intended is unauthorized. If you are not the intended recipient (or responsible for delivery of the message to such person), you may not use, copy, distribute or deliver to anyone this message (or any part of its contents ) or take any action in reliance on it. In such case, you should destroy this message, and notify us immediately. If you have received this email in error, please notify us immediately by e-mail or telephone and delete the e-mail from any computer. If you or your employer does not consent to internet e-mail messages of this kind, please notify us immediately. All reasonable precautions have been taken to ensure no viruses are present in this e-mail. As our company cannot accept responsibility for any loss or damage arising from the use of this e-mail or attachments we recommend that you subject these to your virus checking procedures prior to use. The views, opinions, conclusions and other informations expressed in this electronic mail are not given or endorsed by the company unless otherwise indicated by an authorized representative independent of this message
Note: Privileged/Confidential information may be contained in this message and may be subject to legal privilege. Access to this e-mail by anyone other than the intended is unauthorized. If you are not the intended recipient (or responsible for delivery of the message to such person), you may not use, copy, distribute or deliver to anyone this message (or any part of its contents ) or take any action in reliance on it. In such case, you should destroy this message, and notify us immediately. If you have received this email in error, please notify us immediately by e-mail or telephone and delete the e-mail from any computer. If you or your employer does not consent to internet e-mail messages of this kind, please notify us immediately. All reasonable precautions have been taken to ensure no viruses are present in this e-mail. As our company cannot accept responsibility for any loss or damage arising from the use of this e-mail or attachments we recommend that you subject these to your virus checking procedures prior to use. The views, opinions, conclusions and other informations expressed in this electronic mail are not given or endorsed by the company unless otherwise indicated by an authorized representative independent of this message

**Comment by psignoret** [comment]
Does this file exist: `<yourblog>/wp-content/plugins/aad-sso-wordpress/aad-sso-wordpress.php`?

**Comment by jksus** [comment]
Hello, I am experiencing a similair problem. I followed the instruction set and still have the same old WP login page. Any suggestions as to where I may have gone astray? I should note that I am receiving an error in the dashboard: "Azure Active Directory Single Sign-on for WordPress requires a Settings.json file to be added to the plugin."

**Comment by bradkovach** [comment]
@jksus Create a Settings.json file and add the line to your wp-config.php

```define( 'AADSSO_SETTINGS_PATH', '/path/to/Settings.json' );```

**Comment by jksus** [comment]
I did that as part of the original instruction set. Error message remains.

**Comment by psignoret** [comment]
Can you share how you've set this in `wp-config.php`?

**Comment by bradkovach** [comment]
@jksus a lot of improvements have been made to the plugin to make it easier to configure.  the latest version of the plugin does not require a settings.json file.

**Comment by jksus** [comment]
@bradkovach perhaps I am not running the latest version of the Plugin as the readme file instructs the use of the Setting.json. I am running version 0.4a. Which version is the latest and how to I acquire it?

**Comment by psignoret** [comment]
0.6a is the latest, you can acquire it the same way you installed it the first time.

The README hasn't been updated yet, but once you copy the `aad-sso-wordpress` folder into in `wp-content/plugins/`, when you sign in to the admin page (and activate the plugin), you'll see a new settings page under **Settings** > **Azure AD** where you can set all the fields that you would have set in your JSON file.

**Comment by jksus** [comment]
Forgive me, but when I click the link for Download ZIP, I still get the .4a version. I am not sure how to find the .6a version.

**Comment by psignoret** [comment]
You might want to first remove the old version, and then copy in the new version from: https://github.com/psignoret/aad-sso-wordpress/archive/master.zip

**Comment by psignoret** [comment]
I'm going to close this for now. Feel free to open it again if you're still having this issue with the latest version of the plugin.
