### ISSUE TITLE
Settings.json contains Azure AD access tokens/secrets and can be viewed publicly.

### ISSUE THREAD

**Issue by bradkovach** [psignoret/aad-sso-wordpress#36]
It is possible to load and view the Settings.json file by navigating to it with an HTTP request.  For the most part, these credentials SHOULD BE read-only, but there is a possibility that these credentials would include the ability to write to AD.

This could be expose a serious attack vector for users that haven't properly configured their Azure AD tokens.

1. Saving these credentials to a PHP constant in `wp-config.php`.
2. Saving these credentials to a PHP environment variable `$_ENV['ad_client_token']`
3. Mimic WordPress' behavior where these settings files can be placed one directory above the public html directory
4. Save these credentials to WordPress DB and allow configuration via WordPress administration.

**Comment by bradkovach** [comment]
Fixed in https://github.com/bradkovach/aad-sso-wordpress/commit/55308e4d4e38a200d6263813b2444f85661e7ba8.

**Comment by psignoret** [comment]
Fixed in psignoret@c919244d1ce02c9a4802fe4dcb5c89bb2d065af6, thanks!
