### ISSUE TITLE
Add activation/deactivation/uninstall hooks

### ISSUE THREAD

**Issue by psignoret** [psignoret/aad-sso-wordpress#41]
https://developer.wordpress.org/plugins/the-basics/activation-deactivation-hooks/

**Comment by bradkovach** [comment]
Currently working on UI fixes.  The "deactivation" hook should delete the "aadsso_settings" key and the "activate" hook should fill it with sane defaults.

**Comment by psignoret** [comment]
No, I think only uninstall should remove the settings.

Here's what I'm doing:

- Activate: Check for settings. If present, do nothing. If not present (e.g. first install), set a basic template (it will be incomplete, but that's fine).
- Deactivate: Nothing.
- Uninstall: Remove `aadsso_settings`.

**Comment by psignoret** [comment]
Fixed by #56
