### ISSUE TITLE
Add caching to prevent HTTP request every time `openid_configuration_endpoint` is added to settings

### ISSUE THREAD

**Issue by bradkovach** [psignoret/aad-sso-wordpress#43]
Hour-long expiration should be safe?

**Comment by psignoret** [comment]
Hmmm... I thought I already had one for this, but I'm confusing with my other AAD project. YES, caching is absolutely needed.

Yes, let's start with a simple 1-hour cache. There's some additional logic to be implemented, later, for gracefully handling an emergency signing key rollover, but it's much lower priority.

**Comment by bradkovach** [comment]
ok.  will add to current batch of changes.  should improve performance quite a bit.  Is it known if the `openid_configuration_endpoint` is a versioned API?

**Comment by psignoret** [comment]
No, not versioned.

**Comment by bradkovach** [comment]
done! check my pull request @psignoret
