### ISSUE TITLE
Feature request - ability to change redirect_uri via settings

### ISSUE THREAD

**Issue by tasgray** [psignoret/aad-sso-wordpress#57]
Hi Philippe,

Great plugin, thank you for your efforts. 

I ran in to an issue when configuring it on our site, as we have enhanced security using iThemes Security Pro plugin which allows you to hide the typical wordpress login urls /wp-admin/, /wp-login.php, etc and replace them with a custom one such as /secretloginpage/. This means I have to set the reply url in my azure ad application to /secretloginpage/ instead of /wp-login.php. However this creates an issue because the redirect_uri parameter in the login link query string is harded coded on line 49 of aad-sso-wordpress.php to wp_login_url() which produces a url ending in /wp-config.php. This causes an error in Azure AD - Error: AADSTS50011: The reply address ‘https://someurlhere’ does not match the reply addresses configured for the application: c6827548-2019-4372-8ab8-44a7358be82c.

It would be very handy if redirect_uri variable could be overridden on the settings page instead of resorting to modifying the plugin code which I've done as a temporary work around.

Many thanks

**Comment by psignoret** [comment]
Great point. A simple work-around is actually to remove the `redirect_uri` parameter from the authorization request -- Azure AD will actually default to the first reply URL you've registered.

But still, this should be configurable, and it's fairly simple update. Will probably push this one out this weekend (or today, even).

**Comment by psignoret** [comment]
Done, `redirect_uri` and `logout_redirect_uri` are now configurable. The default still `wp_login_url()`, but you can set whatever you want. (Closed in #59.)

**Comment by bradkovach** [comment]
@tasgrey if you can, please edit your initial request to remove your
application's ID.  The less "production" information we publish, the better.

On Sat, Feb 27, 2016 at 6:12 PM, Philippe Signoret <notifications@github.com
> wrote:

> Done, redirect_uri and logout_redirect_uri are now configurable. The
> default still wp_login_url(), but you can set whatever you want. (Closed
> in #59 <https://github.com/psignoret/aad-sso-wordpress/pull/59>.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psignoret/aad-sso-wordpress/issues/57#issuecomment-189756217>
> .
>



-- 
Brad Kovach
https://bradkovach.com

PGP key available at https://bradkovach.com/pgp
If you need/want to send me an encrypted message, visit
https://bradkovach.com/message

**Comment by psignoret** [comment]
@bradkovach Just for the record: App IDs are not secrets, they're easily discoverable by watching any site's sign-in flow.

**Comment by tasgray** [comment]
@psignoret thank you for making the update so quickly.

@bradkovach I have removed the application ID. Apologies for that.
