### ISSUE TITLE
Where do I find the Azure Group Object ID?

### ISSUE THREAD

**Issue by alefort** [psignoret/aad-sso-wordpress#66]
Thank you for a wonderful plugin that has so far worked well for authenticating users without groups. We are trying to connect users to groups but cannot find the Azure Group Object ID for the groups we want to map into WordPress.

Can you direct me as to where I can find these IDs?

**Comment by psignoret** [comment]
From the Azure portal -> Active Directory -> (Directory) -> Groups -> (Group) should have it.

Alternatively, you can use the Azure AD PowerShell module:

```PowerShell
Get-MsolGroup -SearchString "<group name>"
```

Or Graph Explorer (https://graphexplorer.cloudapp.net) -> Sign in -> `https://graph.windows.net/(domain name or tenant ID)/groups`.

**Comment by alefort** [comment]
That did the trick! Thanks!
