### ISSUE TITLE
Any thoughts on supporting Azure AD B2C

### ISSUE THREAD

**Issue by jblanier02** [psignoret/aad-sso-wordpress#67]
Any thoughts on support for Azure AD B2C Directory?

**Comment by psignoret** [comment]
Apologies for the late response. I do have thoughts on supporting Azure AD B2C. Right now priorities are:

1. Getting the plugin submitted to the official WordPress plugin directory (for upgrades, etc.).
2. A few minor usability and feature enhancements (nothing too big).
3. Support for group picker, B2C, etc.

**Comment by psignoret** [comment]
I've added #70 to track the specific feature of supporting B2C.

**Comment by psignoret** [comment]
I'm going to close this for now, with issue #70 specifically tracking B2C (if by then there isn't already a plugin ([ahem](https://github.com/AzureAD/active-directory-b2c-wordpress-plugin-openidconnect))) that does this.
