### ISSUE TITLE
Mapping Azure AD Group to Custom WP Role

### ISSUE THREAD

**Issue by alefort** [psignoret/aad-sso-wordpress#69]
In your documentation for the AzureAD to WP role mapping, you have the following note:

Valid values for roles are `'administrator'`, `'editor'`, `'author'`, `'contributor'`, `'subscriber'` and `''` (empty string).

Is this the only valid values? We have custom roles created in WP with custom capabilities and we want AzureAD groups to map to these custom roles. Can it be done?

**Comment by psignoret** [comment]
Are you using the latest version of the plugin, that has a settings page?

In the settings page (`Settings` > `Azure AD`), under "WordPress role to Azure AD group map", you should see all roles listed, including custom roles.

**Comment by alefort** [comment]
We are still using the version that has settings in the Settings.json file only.

**Comment by psignoret** [comment]
I *strongly* recommend upgrading. If you leave the Settings.json file, the new version should detect it, and offer to import the settings (and delete the file, which poses non-trivial security risks).

**Comment by bradkovach** [comment]
For the record, any valid role slug should work, even with the old `Settings.json` files.

**Comment by alefort** [comment]
All is well now. Not sure what was causing the issue originally. As @bradkovach mentioned, it should have worked with the old settings, however I found a note in the documentation for the older plugin that listed only the default groups.

The new plugin works, so I'm going to close the comment.
