### ISSUE TITLE
Assign Multiple Roles

### ISSUE THREAD

**Issue by alefort** [psignoret/aad-sso-wordpress#73]
Our requirements are such that we need to apply more than one AD role to WordPress users. Your logic in `update_wp_user_roles` is only capable of assigning one role. I've modified it slightly to use `add_role` instead of `set_role` since `set_role` wipes out any previously assigned roles.

Is this something you would want to include in your plugin?

Cheers

**Comment by psignoret** [comment]
Sounds interesting. It would be important to *only* assign the roles that they were eligible for (and wipe it any previous ones), but I do agree that there's no reason to limit it to a single role.

Send a pull request, I'd welcome the contribution!

**Comment by psignoret** [comment]
This is addressed in #90. Thanks!
