### ISSUE TITLE
User unable to access the admin panel

### ISSUE THREAD

**Issue by TheMetroGuy** [psignoret/aad-sso-wordpress#76]
I created AD application and linked the plugin with AD.

Users are able to login when I set the default role to 'Administrator'. But when the role is set to anything else like 'Author' or 'Editor' etc then they are able to login and see the top black bar on the site but not edit or post anything.

Accessing /wp-admin is showing 'You are not allowed to access this part of the site'.

Any idea what could be the issue?

**Comment by psignoret** [comment]
Would you mind sharing how you've configured the plugin (don't need any actual IDs and definitely not the secrets, just what you've set the checkboxes and drop downs to.

**Comment by TheMetroGuy** [comment]
Find the screenshot here
https://drive.google.com/file/d/0B1syX0dZAWTyX3RjMFdCbGlYWFk/view

**Comment by psignoret** [comment]
@TheMetroGuy I'm going through open issues, and I just realized I never saw your reply -- I do apologize. Since it's been so long, I'm going to close this issue, but if you're still having any problems, please feel free to open it up again and we can investigate what's going on.
