### ISSUE TITLE
Logon only succeeds for one user

### ISSUE THREAD

**Issue by eduh** [psignoret/aad-sso-wordpress#77]
We did setup the plugin\azure according to the readme and were very happy that it worked out of the box. However the login+provisioning only succeeds for one person (me)  which is very strange. 
We do not do anything with role\groups so that may not be the issue. Authentication at the adfs server at our institution succeeds but Wordpress is throwing you away. Is there any way to get debug info from the plugin ? 

One other we noticed is that we had to tick both delegated permissions although we did not configure any group\role mapping
This is url we configured in plugin\azure http://ideescout.azurewebsites.net/wp-login.php

**Comment by psignoret** [comment]
What error message are you getting?

Can you share how you've configured the plugin?

**Comment by eduh** [comment]
![azure](https://cloud.githubusercontent.com/assets/1076033/15179644/66556378-177d-11e6-9420-b6d81a4f9eea.png)

This is the config ...all others options are left unselected or blank.
The error does not live in the Wordpress site. When it fails you are redirected to th e ADFS server with a dutch message saying something like 'we have received a invalid request'

**Comment by eduh** [comment]
BTW:  I can give you access to our wp site if that helps. It is in a testphase

**Comment by psignoret** [comment]
First try copying the Client ID (a Guid) instead of the App ID URI into the client ID field.

**Comment by eduh** [comment]
Will do...only I'm away for a few weeks now ....so will continue begin june

**Comment by eduh** [comment]
Although I'm still confused that it works for only one account.....is it possible it relates to permissions on the AD ?

**Comment by psignoret** [comment]
I need to know what error message you're getting. Is it an error from Azure AD (login.microsoftonline.com)? Or is it an error from your AD FS? If it's an error in Azure AD, what is the specific error message (at the bottom)?

Do you see this error when you try accessing this on a new session (e.g. Chrome's "incognito" mode)?

**Comment by eduh** [comment]
Things get stranger. One of my collegues has a successful login after many retries......  Will check further in june.

**Comment by psignoret** [comment]
Ok, but please send me more details on the error message you get. There's very little I can do with the information you've provided so far.

**Comment by eduh** [comment]
Will do ...in june. Keep you informed.

**Comment by psignoret** [comment]
It's July now. :) Did you get a chance to reproduce this?

**Comment by eduh** [comment]
Hi,
Sorry for not getting back earlier. I did some testing right now with three other persons and every logon was succesful.  I will do some testing with the guys where the initial login failed but they are out of office until next week so I will get back and let you know if the problem has dissappeared. But for now it looks if the  problem does not occur.

**Comment by eduh** [comment]
Hi,
Just got  testresults back from the the other collegues and yes...they can logon without any problem. So it looks like the problem is solved. Perhaps there was some latency between all the config changes in Azure....  Problem solved and thanks for the assistence
