### ISSUE TITLE
Groups not applying

### ISSUE THREAD

**Issue by laiello** [psignoret/aad-sso-wordpress#78]
Hello,

I've configured this on a wordpress site and its working great, very good work. Unfortunately, the group assignments are not working correctly. 

I've added the group object ID from azure AD, however when I login, no role is being assigned (just Subscriber, which is default). If I manually give myself administrator and then login again, it reverts back to Subscriber so that part is working at least.

I'm not quite sure what next steps I can use to debug this.

Thanks

**Comment by psignoret** [comment]
I'm assuming your configuration looks like the following:

![image](https://cloud.githubusercontent.com/assets/231140/15491480/9d01e8e0-2125-11e6-9e02-29376de6c9c4.png)

(If it doesn't, then let me know.) If so, then the only reason I can think of for this to fail is if the request to check the authenticated user's group membership is either (a) failing completely, or (b) not finding that the user is a member of any of the groups you've specified and thus falling back to your default.

Let's start with some basics, and if that doesn't work, we can go into some more advanced debugging. Try the following:

- Confirm the group object ID is, in fact, the Azure AD object ID. A good way to verify this is to go to https://graphexplorer.cloudapp.net, sign in as that user, and make a GET request for: <br>
    `https://graph.windows.net/{tenant-id-or-domain}/{group-id}`<br>
Where `{group-id}` is the same group object ID. The response should be some details about the group.
- Confirm that the user is actually a member of that group (directly or indirectly, through nested groups).
- Check for typos such as spaces before or after the object ID.
- Check that you have assigned the application the correct delegated permissions (see the [README](https://github.com/psignoret/aad-sso-wordpress/blob/master/README.md)).

**Comment by laiello** [comment]
That's a valid assumption.

I tried the graphexplorer and I get a: Request_ResourceNotFound when querying:

https://graph.windows.net/MYDOMAIN.com/GROUPOBJECTID

I have confirmed that the groupID matches the Azure COnsole (in fact, it doesn't find any of them).

The delegated permissions are like this:

![2016-05-24 03_46_58-active directory - microsoft azure](https://cloud.githubusercontent.com/assets/671054/15501432/45cbb3b6-2162-11e6-9d4f-39639d0591ef.png)

**Comment by psignoret** [comment]
It sounds like you have the object ID wrong, or you are providing object IDs of groups that are in a different directory. Where, specifically, are you getting the object IDs from? Is there a chance the user you're signing in as is actually in a different directory ("sourced from another Azure AD", in the 'USERS' list in Azure AD)?

**Comment by laiello** [comment]
"Sourced From" is "Microsoft Azure Active Directory" in the Users tab

I am getting the object IDs by selecting the group and then going to the Properties tab
![2016-05-24 15_36_50-active directory - microsoft azure](https://cloud.githubusercontent.com/assets/671054/15522158/5e15b7b0-21c5-11e6-8de8-a030fd9277d7.png)

**Comment by psignoret** [comment]
Oh, I just realized I made a mistake earlier: can you try the Graph Explorer thing again, but with this path:

    https://graph.windows.net/{tenant-id-or-domain}/groups/{group-id}

**Comment by laiello** [comment]
Thanks, looks like I am making some headway, now receiving:

ERROR: AAD user USER@MYDOMAIN.com is not a member of any group granting a role.

This seems to be working on my test side, but not production (two different "applications" with their own client ID/secret) - The Role/Group mappings are the same.

**Comment by psignoret** [comment]
Can you send me a message to philippe.signoret [at] outlook.com? (We'll report back as soon as we have a resolution.)

**Comment by psignoret** [comment]
@laiello I'm going to close this issue for now. If you're still experiencing this problem, please feel free to re-open it and we can dig into the problem.
