### ISSUE TITLE
init action causing PHP session for every visitor

### ISSUE THREAD

**Issue by stephen-kainos** [psignoret/aad-sso-wordpress#85]
```
 // Add the hook that starts the SESSION
 add_action( 'init', array( $this, 'register_session' ) );
```

Appears to create a PHP session as intended, however it creates a new session for every visitor of the website even if they are not logging in. This can effect websites behind reverse proxies such as Varnish, as they would be configured to not cache active sessions. 

I've successfully moved this action to the login_init

```
// Add the hook that starts the SESSION
add_action( 'login_init', array( $this, 'register_session' ) );
```

Everything still appears to be working as expected, including a user session not being created for each user. I'll submit a pull request for this small change.

**Comment by psignoret** [comment]
Thanks for finding this, and proposing a fix! A few minor notes:

- The session needs to be started before `save_redirect_and_maybe_bypass_login`, which also hooked by `login_init`, so adding explicit [priority](https://developer.wordpress.org/reference/functions/add_action/#parameters) may be a good idea.
- [Functions that currently use `$_SESSION`](https://github.com/psignoret/aad-sso-wordpress/search?utf8=%E2%9C%93&q=SESSION) should be reviewed to ensure they are all executed after `login_init`.

**Comment by stephen-kainos** [comment]
I've had a look through the functions using $_SESSION and they all appears to be initiated from the `authenticate()` pluggable function. Since this is called on the login form submission then having the $_SESSION creation on the login_init, when the login form is initialised should be okay. 

I'll add in a priority between the 2 login_init actions and submit a pull request for this

**Comment by psignoret** [comment]
Just one correction (irrelevant to your conclusion): `AADSSO::authenticate` is called whenever `wp-login.php` is loaded, with `action=login` (or no `action`, which default to `login`), not when the login form is submitted. As an example, this is the call path for an unauthenticated user visiting `.../wp-login.php` (line numbers and links for WordPress 4.5.3):

1. `wp_signon(, )` called at [`wp-login.php:784`](https://github.com/WordPress/WordPress/blob/b15f7577d37e042d4a534688c7178647d4e358c8/wp-login.php#L784)
2. `wp_authenticate(, )` called at [`wp-includes/user.php:83`](https://github.com/WordPress/WordPress/blob/b15f7577d37e042d4a534688c7178647d4e358c8/wp-includes/user.php#L83)
3. `apply_filters(authenticate, , , )` called at [`wp-includes/pluggable.php:529`](https://github.com/WordPress/WordPress/blob/b15f7577d37e042d4a534688c7178647d4e358c8/wp-includes/pluggable.php#L529)
4. `call_user_func_array(Array ([0] => AADSSO Object (...),[1] => authenticate), Array ([0] => ,[1] => ,[2] => ))` called at [`wp-includes/plugin.php:235`](https://github.com/WordPress/WordPress/blob/b15f7577d37e042d4a534688c7178647d4e358c8/wp-includes/plugin.php#L235)
5. `AADSSO->authenticate(, , )`

In either case, `login_init` is invoked whenever `login.php` is loaded (regardless of what the `action` is), so I think this is a safe change for now.

Looking forward to the PR!

**Comment by stephen-kainos** [comment]
sorry, you are completely correct. I misread the documentation there.

Submitting a pull request for this now
